name: DSLAB Image Build Script

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull the latest existing_image
      run: docker pull nginx:latest
      
    - name: Get Git commit SHA
      id: git-sha
      run: |
        git fetch --tags
        git_rev=$(git rev-parse --short HEAD)
        echo "::set-output name=git_sha::${git_rev}"

    - name: Get current date
      id: get-date
      run: echo "::set-output name=current_date::$(date +'%Y-%m-%d')"

    - name: Retrieve version number
      id: get-version
      run: |
        cat version.txt

    - name: Increment version number
      id: increment-version
      run: |
        version=$(cat version.txt)
        new_version=$((version + 1))
        echo "$new_version" > version.txt
        echo "GIT_COMMIT: $GITHUB_SHA" >> version.txt
        echo "Date: $(date +'%Y-%m-%d')" >> version.txt
        echo "Version: $new_version" >> version.txt
        # version=$(cat version.txt)
        # new_version=$((version + 1))
        # echo $new_version > version.txt
        # echo "::set-output name=version::${new_version}"
        # echo "GIT_COMMIT: ${git_rev}" >> version.txt
        # echo "Date: $(date +'%Y-%m-%d') >> version.txt
        # echo "Version: $new_version" >> version.txt
      
    - name: Commit updated version.txt
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
      run: |
        git config --global user.email "khetanpawar93@gmail.com"
        git config --global user.name "khetan4"
        git add version.txt
        git commit -m " Increment version.txt"
        git push
        
    - name: Build Docker image
      run: |
        version=$(cat version.txt)
        docker build -t new_image_name:v$version .

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region AWS_REGION | docker login --username AWS --password-stdin AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com

    - name: Tag the Docker image
      run: |
        version=$(cat version.txt)
        docker tag new_image_name:v$version AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/new_image_name:v$version

    - name: Push to Amazon ECR
      run: |
        version=$(cat version.txt)
        docker push AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/new_image_name:v$version
